@startuml

namespace AsyncTcp {
    class ContextManager {
        - async_context_threadsafe_background_t background_ctx
        - async_context_t* ctx
        - bool initiated

        --
        + ContextManager()
        + ~ContextManager()
        + bool init()
        + bool addWorker(PerpetualWorker &)
        + bool addWorker(EphemeralWorker &, uint32_t delay = 0)
        + bool removeWorker(Worker &)
        + bool removeWorker(EphemeralWorker &)
        + void setPending(Worker &)
        + uint32_t execute(HandlerFunction, void*) const
        + void acquireLock() const
        + void releaseLock() const
        + void checkLock() const
        + void waitUntil(absolute_time_t until) const
        + uint8_t getCore() const
    }
}

@enduml